version: '3.3'

services:
    heartbeat:
        image: nailbiter/heartbeat_system
        command: python3 heartbeat.py
    scheduler:
        image: nailbiter/heartbeat_system
        environment:
            - FLASK_ENV=development
            - MONGO_URL=${MONGO_URL}
            - TIMERS_COLL=pyscho_timers
    telegram_client:
        image: nailbiter/universal-telegram-client
        environment:
            - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
            - SCHEDULER=telegram_server:5000
            - CHAT_ID=${CHAT_ID}
            - MESSAGE_CB=message
            - TELEGRAM_COMMANDS=psycho,ls
    telegram_server:
        build:
            context: context
        environment:
            - SCHEDULER=scheduler:5000
            - SELF_URL=telegram_server:5000
            - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
            - MONGO_URL=${MONGO_URL}
            - FLASK_ENV=development
            - FLASK_APP=server.py
