version: '3.3'

services:
    telegram_client:
        image: nailbiter/universal-telegram-client
        environment:
            - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
            - SCHEDULER=telegram_server:5000
            - CHAT_ID=${CHAT_ID}
            - COMMANDS=psycho
            - MESSAGE_CB=message
            - TELEGRAM_COMMANDS=psycho
    telegram_server:
        build:
            context: .
        command: flask run --host=0.0.0.0
        environment:
            - SCHEDULER=scheduler:5000
            - SELF_URL=telegram_server:5000
            - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
            - MONGO_URL=${MONGO_URL}
            - FLASK_ENV=development
            - FLASK_APP=server.py
